version: "3.5"

services:
  rustapp:
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      - DATABASE_URL=postgres://postgres:my-secure-password@postgres:5432/crud

    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15.5-alpine3.18
    ports:
      - "5432:5432"

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=my-secure-password
      - POSTGRES_DB=crud
      - TZ=America/Sao_Paulo

    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
